# Generated by Django 4.1.5 on 2024-01-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='credit',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_companies',
            field=models.TextField(),
        ),
    ]
